//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DW2SMT.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DW2SMT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DW2SMT {
            get {
                object obj = ResourceManager.GetObject("DW2SMT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DW2SMT_Large {
            get {
                object obj = ResourceManager.GetObject("DW2SMT Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap editicon {
            get {
                object obj = ResourceManager.GetObject("editicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] Map {
            get {
                object obj = ResourceManager.GetObject("Map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 20= 
        ///21=!
        ///22=&quot;
        ///23=#
        ///24=$
        ///25=%
        ///26=&amp;
        ///27=&apos;
        ///28=(
        ///29=)
        ///2A=*
        ///2B=+
        ///2C=,
        ///2D=-
        ///2E=.
        ///2F=/
        ///30=0
        ///31=1
        ///32=2
        ///33=3
        ///34=4
        ///35=5
        ///36=6
        ///37=7
        ///38=8
        ///39=9
        ///3A=:
        ///3B=;
        ///3C=&lt;
        ///3D==
        ///3E=&gt;
        ///3F=?
        ///40=@
        ///41=A
        ///42=B
        ///43=C
        ///44=D
        ///45=E
        ///46=F
        ///47=G
        ///48=H
        ///49=I
        ///4A=J
        ///4B=K
        ///4C=L
        ///4D=M
        ///4E=N
        ///4F=0
        ///50=P
        ///51=Q
        ///52=R
        ///53=S
        ///54=T
        ///55=U
        ///56=V
        ///57=W
        ///58=X
        ///59=Y
        ///5A=Z
        ///5B=[
        ///5C=\
        ///5D=]
        ///5E=^
        ///5F=_
        ///60=`
        ///61=a
        ///62=b
        ///63=c
        ///64=d
        ///65=e
        ///66=f
        ///67=g
        ///68=h
        ///69=i
        ///6A=j
        ///6B=k
        ///6C=l
        ///6D=m
        ///6E=n
        ///6F=o
        ///70=p
        ///71=q
        ///72=r
        ///73=s
        ///74=t
        ///75 [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string Worms2TABLE {
            get {
                return ResourceManager.GetString("Worms2TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap X_button {
            get {
                object obj = ResourceManager.GetObject("X button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
